services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      tags:
        - "harbour-api:1.0.0"
    # If need to bash into container, uncomment the following line - then run `docker exec -it <container> /bin/bash`
    # command: tail -f /dev/null
    # restart: always
    container_name: harbour-api
    env_file:
      - .env.docker
    environment:
      - DEBUG=1
    ports:
      - "8010:8010"
    volumes:
      - ./data:/src/data
      - ./app:/src/app
    depends_on:
      - db
    
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: '2gb'
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petrov
      - POSTGRES_USER=webapp
      - POSTGRES_DB=webapp

volumes:
  pgdata: